name: flutter_crypto_wallet_ui
description: Modern bir kripto cüzdan arayüzü (Flutter)
version: 1.0.0
publish_to: 'none'

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  fl_chart: ^0.63.0
  local_auth: ^2.1.6

flutter:
  uses-material-design: true
  assets:
    - assets/ 